### PR TITLE
Enable additional linters and fix problems

### PR DESCRIPTION
**Pull request by scottyw**
Two main changes here:

* `golint` wasn't installed in CI nor were we checking it ran correctly so I was seeing errors locally but not in CI
* `golangci-lint` offers a bunch of other checks that look good but were disabled - these are now enabled

Thanks @eoinmcq for the `gosec` file fix which I copy-pasted from your PR to get it all passing.

### CODE REVIEW

**Comment by scottyw** [comment]
I did not make the change to update the lint/gosec tooling every time because it's too slow. I think the current pattern is exactly to address this. It's reliably the latest version in CI and easy to update locally if you need to.

**Comment by eoinmcq** [comment]
Looks good @scottyw . Except for the build failure...

Something go mod tidy related is going on here.

**Comment by scottyw** [comment]
Grand - I'm out next week so I will rebase it week after next. Thanks!

**Comment by scottyw** [comment]
@eoinmcq I was installing "golint" without disabling modules, which affected the mod file and caused the break. Fixed that and rebased. Thanks!

**Pull request merged**
