### PR TITLE
feat: Add additional options to CommmandTask

### LINKED ISSUE #60: [orch] Allow setting description or other options (optionally)
## Use Case
I would like to be able to set a description on the job for `orch.CommandTask` (and probably others)

## Describe the Solution You Would Like
I would like to be able to optionally include additional fields when kicking off a job (CommandTask), such as description. I am thinking a sort of variadic with `map[string]interface{}...` which I think would allow for more flexibility without changing the interface.

## Describe Alternatives You've Considered
Are there any? besides using a different library or making the request directly?

## Additional Context
* https://puppet.com/docs/pe/2019.8/orchestrator_api_commands_endpoint.html#orchestrator_api_post_command_task

### PR DESCRIPTION
**Pull request by TJM**
This adds the ability to set the `description` and `noop` mode.

Closes #60

### CODE REVIEW

**Comment by TJM** [comment]
How do I get a review on this? I'd rather not maintain a fork ;)

**Comment by TJM** [comment]
> I have opened an issue [cla-assistant/cla-assistant#745](https://github.com/cla-assistant/cla-assistant/issues/745) with them. I am not sure what the problem is, but I don't see any sort of agreement. I do see a checkbox, but no "sign" or "submit" ... I assume they are having some sort of outage? I will try to come back again later.

This is resolved. as per above.

**Comment by TJM** [comment]
@eoinmcq Can you please work this one through as well? *thanks* :)

**Comment by TJM** [comment]
*ping* I noticed a merged MR and a new release, but mine was passed by, what do I need to get this merged?

**Review by cliveweir — APPROVED** [review]
Looks good to me

**Comment by cliveweir** [comment]
> _ping_ I noticed a merged MR and a new release, but mine was passed by, what do I need to get this merged?

Hi @TJM I have merged this PR and will include it in the next release. Apologies for the lack of response.

**Pull request merged**
