### PR TITLE
Adopt the pkg convention for the project layout

### PR DESCRIPTION
**Pull request by davejohnston**
This commit moves packages that are intended to be public
under the pkg folder.
This is a common go convention, although not officially part of any
specification.

### CODE REVIEW

**Comment by davejohnston** [comment]
@tphoney @HelenCampbell @scottyw I'm raising this PR to move the public-facing packages under a 'pkg' directory.  This is a pretty common convention used in golang projects to help organize code and is used in projects such as kubernetes, docker etc.

IMO it helps keep the code organized, but I'm happy to take on your opinions about this?

**Comment by scottyw** [comment]
I'm happy to go for it.

**Comment by HelenCampbell** [comment]
Happy for it to be moved if this is the general convention 👍

**Comment by scottyw** [comment]
Cool, let's do it.

**Pull request merged**
